##Spring Configuration
server:
  port: 8080
spring:
  application:
    name: dddDemoJava
  data:
    mongodb:
      host: localhost
      port: 27017
      database: ddd-demo


rabbitmq:
  image: rabbitmq:management
  ports:
    - "5672:5672"
    - "15672:15672"